services:
  server:
    build: .
    ports:
      - 8080:8080
    command: npm start
    environment:
      - ACCESS_TOKEN=GHJFSJDFGSJHD
      - REFRESH_TOKEN=HGSFDKJGHSDKFJGHDFLKKLF
    volumes:
      - ./src/:/app/src/
    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
  client:
    build: ../2104-wns-paris-lama-front/
    ports:
      - 3000:3000
    volumes:
      - ../2104-wns-paris-lama-front/src/:/client/src/
