services:
  server:
    build: .
    ports:
      - 8080:8080
    command: npm start
    volumes:
      - ./src/:/app/src/
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
  client:
    build: ../2104-wns-paris-lama-front/
    ports:
      - 3000:3000
    volumes:
      - ../2104-wns-paris-lama-front/src/:/client/src/
