services:
  server:
    build: .
    command: sh -c "npm run build && npm run prod"
    expose:
      - 5000
    environment:
      - NODE_ENV=production
      - SERVER_PORT=5000
    depends_on:
      - mongodb
    volumes:
      - ./src/:/app/src/
  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
  client:
    build: ../2104-wns-paris-lama-front/
    command: sh -c "npm run build"
    environment:
      - NODE_ENV=production
    volumes:
      - ../2104-wns-paris-lama-front/src/:/client/src/
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - 6969:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - dist:/build
