services:
    server:
            build: .
            ports: 
                - 8080:8080
            command: npm start
            volumes:
                - ./src/:/app/src/
    mongodb:
            image: mongo
            volumes:
                - ./data:/data/db
    client:
            build: ../2104-wns-paris-lama-front/
            ports:
                - 3001:3000
            volumes:
                - ../2104-wns-paris-lama-front/src/:/app/src/
