name: Releases

on:
  push:
    branches: feature
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checks-directory
        run: |
          if [ -d "./.idea" ]; then echo "Forbidden Webstorm folder (.idea/) found ! Please, ignore in .gitignore"; exit 2; fi
          if [ -d "./.vscode" ]; then echo "Forbidden VScode folder (.vscode) found ! Please, ignore in .gitignore"; exit 2; fi
          if [ $(find ./ -name .DS_Store) ]; then echo "Forbidden MacOS boring file (.DS_Store) found ! Please, ignore in .gitignore"; exit 2; fi
          if [ -d "./node_modules" ]; then echo "Forbidden external libs folder (node_modules/) found !"; exit 2; fi
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
          yarn
          yarn lint
          yarn build
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Check out code
        uses: actions/checkout@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: false
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}